name: CI CD

on:
  push:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install

    - name: Build artifact
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: build
        
    - name: upload artifact
      uses: actions/upload-artifact@master
      with:
        name: build
        path: build
        
  deploy:
    needs: [build]
    
    runs-on: ubuntu-latest

    steps:
    - name: download artifact
      uses: actions/download-artifact@master
      with:
        name: build
      
    - name: deploy to S3
      run: |
        aws s3 rm s3://jr-test-111 --recursive
        aws s3 cp . s3://jr-test-111/ --recursive
      env:
        AWS_DEFAULT_REGION: ap-northeast-1
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
